### ISSUE TITLE
Username validation doesn't work

### ISSUE THREAD

**Issue by aerni** [edalzell/statamic-profiler#23]
When updating a user profile with `{{ profiler:edit_form }}`, the username validation is ignored. The validation works as expected when registering a user with `{{ user:register_form }}`.

In my `users.yaml`:

```yaml
username:
  type: text
  validate: required|min:3|alpha_dash
```
